### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by bilAlid** [mleczakm/monolog-sentry-bundle#5]
Hello,

I'm using your bundle and it's really good for your project !
I wonder if you plan to add user's **roles** in data displayed in Sentry ?

**Comment by mleczakm** [comment]
I don't know if it is possible in easy way, but I will try :)

**Comment by bilAlid** [comment]
That would be great :D
Let me know if you need some help

**Comment by mleczakm** [comment]
I've checked and it is not supported by Sentry SDK 1.9 - user scope doesn't have `role` or `roles` - so I won't add this to this package, because it would only make logs less readable with no real value. You can add it by yourself with ease, just make your own service modifying a bit `Dziki\MonologSentryBundle\SubscribedProcessor\UserDataAppending`, extract roles instead of name and add their values either to tags or extra context, then tag service as `monolog.processor` and voila :)

**Comment by bilAlid** [comment]
Thank you very much, I'll try it 👍
